apiVersion: storage.example.com/v1alpha1
kind: StorageAccountClaim
metadata:
  name: salarstest2134
  namespace: crossplane-system
spec:
  location: eastus
  resourceGroupName: rg-sa-lars
  storageAccount:
    accountTier: Standard
    accountReplicationType: LRS
    accountKind: StorageV2
    accessTier: Hot
    minTlsVersion: TLS1_2
    httpsTrafficOnlyEnabled: true
    allowBlobPublicAccess: false
